// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSwpDkjEpGFu9CewTUV_O23yS7oS4TQyA',
    appId: '1:623568998373:web:b697827910a909ca7ca90c',
    messagingSenderId: '623568998373',
    projectId: 'flutter-firebase-c7151',
    authDomain: 'flutter-firebase-c7151.firebaseapp.com',
    storageBucket: 'flutter-firebase-c7151.firebasestorage.app',
    measurementId: 'G-3BB05LY0J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_Nd3YmMizEPebA2-_1ItUdxk9AdJ1xY',
    appId: '1:623568998373:android:d344bf3190f233257ca90c',
    messagingSenderId: '623568998373',
    projectId: 'flutter-firebase-c7151',
    storageBucket: 'flutter-firebase-c7151.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSwpDkjEpGFu9CewTUV_O23yS7oS4TQyA',
    appId: '1:623568998373:web:1b694ed5a06883c57ca90c',
    messagingSenderId: '623568998373',
    projectId: 'flutter-firebase-c7151',
    authDomain: 'flutter-firebase-c7151.firebaseapp.com',
    storageBucket: 'flutter-firebase-c7151.firebasestorage.app',
    measurementId: 'G-2LQ6YNLBSR',
  );
}
